/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ClienteDAO;
import javax.swing.JOptionPane;


import vistas.Menu;

/**
 *
 * @author anthoni
 */
public class Clientes extends javax.swing.JFrame {

    ClienteDAO dao=new ClienteDAO();
    Cliente cl=new Cliente();
    
    public String modo;
   
    
   DefaultTableModel modelo= new DefaultTableModel();
    public Clientes() {
        initComponents();
        
        Iniciar();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        PanelCli.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCli = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        comboSexo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        PanelCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new Color(0,0,0,0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bnt-actualizar.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setOpaque(false);
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-actualizarP.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        PanelCli.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 770, 240, 70));

        btnEliminar.setBackground(new Color(0,0,0,0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-eliminarcli.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setOpaque(false);
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-eliminarcliP.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelCli.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 770, 240, 70));

        txtApellido.setBackground(new Color(0,0,0,0));
        txtApellido.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtApellido.setBorder(null);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        PanelCli.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 325, 330, 30));

        txtDni.setBackground(new Color(0,0,0,0));
        txtDni.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtDni.setBorder(null);
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        PanelCli.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 453, 220, 30));

        txtNumero.setBackground(new Color(0,0,0,0));
        txtNumero.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNumero.setBorder(null);
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        PanelCli.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 220, 30));

        btnAgregar.setBackground(new Color(0,0,0,0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGAR.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.setOpaque(false);
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGARp.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        PanelCli.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 770, 230, 70));

        txtNombre.setBackground(new Color(0,0,0,0));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        PanelCli.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 215, 330, 30));

        tabla.setBackground(new java.awt.Color(255, 255, 204));
        tabla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tabla.setForeground(new java.awt.Color(102, 102, 102));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDO", "NUMERO", "SEXO", "Id"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        PanelCli.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 790, 560));

        jButton3.setBackground(new Color(0,0,0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jButton7.setBackground(new Color(0,0,0,0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-C.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-CEP.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        comboSexo.setBackground(new java.awt.Color(166, 163, 111));
        comboSexo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        comboSexo.setForeground(new java.awt.Color(166, 163, 111));
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "M", "F" }));
        comboSexo.setBorder(null);
        comboSexo.setOpaque(false);
        comboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSexoActionPerformed(evt);
            }
        });
        PanelCli.add(comboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 705, 180, 40));

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iraVentas.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sombrairVentas.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 920, -1, 110));

        jButton2.setBackground(new Color(0,0,0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iraProductos.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sombrairaproductos.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 910, -1, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BackgroudCliente.png"))); // NOI18N
        PanelCli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        txtidCliente.setBackground(new Color(0,0,0,0));
        txtidCliente.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtidCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidCliente.setBorder(null);
        txtidCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidClienteActionPerformed(evt);
            }
        });
        PanelCli.add(txtidCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 130, 40));

        getContentPane().add(PanelCli);
        PanelCli.setBounds(0, 0, 1360, 1070);

        setSize(new java.awt.Dimension(1354, 1070));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSexoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Menu mn = new Menu();
        mn.setVisible(true);
        mn.mode=modo;
                dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
        limpiar();
         listar();
         idAleatorio();
         nuevo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       actualizar();
       limpiar();
        listar();
        idAleatorio();
        nuevo();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        limpiar();
         listar();
         idAleatorio();
         nuevo();
         
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtidClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidClienteActionPerformed
       
    }//GEN-LAST:event_txtidClienteActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila=tabla.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }else{
            String idCliente=tabla.getValueAt(fila, 5).toString();
        String dni=tabla.getValueAt(fila, 0).toString();
        String nom=tabla.getValueAt(fila, 1).toString();
        String ape=tabla.getValueAt(fila, 2).toString();
        String numero=tabla.getValueAt(fila, 3).toString();  
        String sexo=tabla.getValueAt(fila, 4).toString();
        
        txtidCliente.setText(idCliente);
        txtDni.setText(dni);
        txtNombre.setText(nom);
        txtApellido.setText(ape);
        txtNumero.setText(numero);
        comboSexo.setSelectedItem(sexo);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Productos Po = new Productos();
        Po.setVisible(true);
        Po.modo=modo;
                dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Venta Vt = new Venta();
        Vt.setVisible(true);
        Vt.modo=modo;
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Diseño();
    }//GEN-LAST:event_formWindowActivated

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
                char TipoTecla=evt.getKeyChar();
        if(Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
                char TipoTecla=evt.getKeyChar();
        if(Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
       if( txtDni.getText().length()>8){
            evt.consume();
        }
        
        char TipoTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if( txtNumero.getText().length()>12){
            evt.consume();
        }
        
        char TipoTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroKeyTyped
    void Diseño(){
    if("0".equals(modo)){
             jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BackgroudCliente.png"))); // NOI18N
         }else if("1".equals(modo)){
              jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteClaro.png"))); // NOI18N
         }else if("2".equals(modo)){
              jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClienteDarkV.png"))); // NOI18N
         }else {
              jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClienteDarkM.png"))); // NOI18N
         }
}
    void agregar(){
        String idCliente=txtidCliente.getText();
        String dni=txtDni.getText();
        String nom=txtNombre.getText();
        String ape=txtApellido.getText();
        String numero=txtNumero.getText();  
        String sexo=(String) comboSexo.getSelectedItem();
       
      
        
        Object[] ob=new Object[6];
        ob[0]=idCliente;
        ob[1]=dni;
        ob[2]=nom;
        ob[3]=ape;
        ob[4]=numero;
        ob[5]=sexo;
        
         dao.add(ob);
       
    }
    void idAleatorio(){
        
        String idcli=dao.IdCliente();
        int id=Integer.valueOf(idcli);
       txtidCliente.setText(Integer.toString(id+1));
        
    }
    void actualizar(){
        int fila=tabla.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }else{
            String idCliente=txtidCliente.getText();
        String dni=txtDni.getText();
        String nom=txtNombre.getText();
        String ape=txtApellido.getText();
        String numero=txtNumero.getText();  
        String sexo=(String) comboSexo.getSelectedItem();
        
        Object[] ob=new Object[6];
           ob[5]=idCliente;
        ob[0]=dni;
        ob[1]=nom;
        ob[2]=ape;
        ob[3]=numero;
        ob[4]=sexo;
        
         dao.actualizar(ob);
        }      
       
    }
    void eliminar(){
         int fila=tabla.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }else{
            String idCliente=tabla.getValueAt(fila, 5).toString();
            dao.eliminar(idCliente);
        }
    }
    void listar(){
        List<Cliente> lista=dao.listar();
        modelo=(DefaultTableModel)tabla.getModel();
        Object[]ob=new Object[6];
        for(int i=0;i< lista.size();i++){
            ob[0]=lista.get(i).getDNI();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getApellido();
            ob[3]=lista.get(i).getNumero();
            ob[4]=lista.get(i).getSexo();
            ob[5]=lista.get(i).getIdCliente();
            modelo.addRow(ob);
        }
        
        tabla.setModel(modelo);
    }
    void nuevo(){
          
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtNumero.setText("");
        comboSexo.setSelectedItem("Seleccionar");
        txtNombre.requestFocus();
        
    }
    void limpiar(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    
    
    void Iniciar(){
        idAleatorio();
        listar();
        txtidCliente.setVisible(false);
         
       
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCli;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtidCliente;
    // End of variables declaration//GEN-END:variables
}
