package vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import modelo.EntidadUsuario;
import modelo.UsuarioDAO;
import vistas.instaaa;

/**
 *
 *
 */
public class Menu extends javax.swing.JFrame {

    UsuarioDAO udao = new UsuarioDAO();
    EntidadUsuario eu = new EntidadUsuario();

    Venta v = new Venta();
    public String mode,user,pass,id,nivel;
   

    public Menu() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        PanelMenu.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        modo = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        PanelMenu.setMinimumSize(new java.awt.Dimension(1600, 100));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sales.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salesP.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salesF.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 280, 260));

        jButton2.setBackground(new Color(0,0,0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Products.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProductsP.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProductsF.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 340, 260));

        jButton3.setBackground(new Color(0,0,0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informe.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informeP.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informeF.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 300, 260));

        jButton4.setBackground(new Color(0,0,0,0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleadosP.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleadosF.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 340, 260));

        jButton5.setBackground(new Color(0,0,0,0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Proveedores.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setOpaque(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProveedoresP.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProveedoresF.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 350, 260));

        jButton6.setBackground(new Color(0,0,0,0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientessss.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setOpaque(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteP.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientef.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 300, 260));

        jButton8.setBackground(new Color(0,0,0,0));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-C.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setOpaque(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-CEP.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        modo.setBackground(new java.awt.Color(51, 255, 102));
        modo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        modo.setForeground(new java.awt.Color(255, 255, 0));
        modo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Dinamico", "Claro", "OscuroV", "OscuroM" }));
        modo.setBorder(null);
        modo.setOpaque(false);
        PanelMenu.add(modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 930, 270, 40));

        jButton7.setBackground(new Color(0,0,0,0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MODOc.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setOpaque(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/presMode.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 910, 81, 81));

        jButton9.setBackground(new Color(0,0,0,0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setOpaque(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infop.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 910, 81, 81));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MainMenu.png"))); // NOI18N
        PanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 1050));

        getContentPane().add(PanelMenu);
        PanelMenu.setBounds(0, 0, 1360, 1050);

        setSize(new java.awt.Dimension(1363, 1055));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Empleados Em = new Empleados();
        Em.setVisible(true);
         Em.modo = mode;
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Clientes Ct = new Clientes();
        Ct.setVisible(true);
        Ct.modo = mode;
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Venta Vt = new Venta();
        Vt.setVisible(true);
        Vt.modo = mode;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Proveedores Pv = new Proveedores();
        Pv.setVisible(true);
        Pv.modo=mode;
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Productos Po = new Productos();
        Po.setVisible(true);
        Po.modo = mode;
        dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        Diseño();


}//GEN-LAST:event_formWindowActivated

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ActualizarModo();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       instaaa fo = new instaaa();
        fo.setVisible(true);
    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Informe Po = new Informe();
        Po.setVisible(true);
   Po.modo = mode;
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    void Diseño() {
        
       
        if ("0".equals(mode)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MainMenu.png"))); // NOI18N
        } else if ("1".equals(mode)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuClaro.png"))); // NOI18N
        } else if ("2".equals(mode)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuDarkV.png"))); // NOI18N
        } else if ("3".equals(mode)){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuDarkM.png"))); // NOI18N
        }
    }

    void ActualizarModo() {

        String Modulo = (String) modo.getSelectedItem();
        if (Modulo == "Dinamico") {
            mode = "0";
        } else if (Modulo == "Claro") {
            mode = "1";
        } else if (Modulo == "OscuroV") {
            mode = "2";
        } else if (Modulo == "OscuroM") {
            mode = "3";
        }
        Object[] ob = new Object[5];
        ob[4] = user;
        ob[0] = pass;
        ob[1] = nivel;
        ob[2] = id;
        ob[3] = mode;

        udao.actualizar(ob);
        Diseño();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> modo;
    // End of variables declaration//GEN-END:variables
}
