package vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Proveedor;
import modelo.ProveedorDAO;
import vistas.Menu;

public class Proveedores extends javax.swing.JFrame {

    ProveedorDAO dao=new ProveedorDAO();
    Proveedor pv=new Proveedor();
    
    DefaultTableModel modelo= new DefaultTableModel();
    public Proveedores() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        PanelCli.setBackground(new Color(0,0,0,0));
        iniciar();
        fechaActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCli = new javax.swing.JPanel();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        txtdireccion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        agregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtidProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        PanelCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setBackground(new Color(0,0,0,0));
        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bnt-actualizar.png"))); // NOI18N
        actualizar.setBorder(null);
        actualizar.setOpaque(false);
        actualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-actualizarP.png"))); // NOI18N
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        PanelCli.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 180, 50));

        eliminar.setBackground(new Color(0,0,0,0));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-eliminarcli.png"))); // NOI18N
        eliminar.setBorder(null);
        eliminar.setOpaque(false);
        eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-eliminarcliP.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        PanelCli.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 180, 50));

        txtdireccion.setBackground(new Color(0,0,0,0));
        txtdireccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtdireccion.setText("484894984");
        txtdireccion.setBorder(null);
        PanelCli.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 310, 40));

        jSeparator4.setForeground(new java.awt.Color(166, 163, 111));
        PanelCli.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 310, 20));

        txtTelefono.setBackground(new Color(0,0,0,0));
        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtTelefono.setText("9586146625");
        txtTelefono.setBorder(null);
        PanelCli.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 310, 40));

        jSeparator8.setForeground(new java.awt.Color(166, 163, 111));
        PanelCli.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 310, 20));

        agregar.setBackground(new Color(0,0,0,0));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGAR.png"))); // NOI18N
        agregar.setBorder(null);
        agregar.setOpaque(false);
        agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGARp.png"))); // NOI18N
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        PanelCli.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 180, 50));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(166, 163, 111));
        jLabel7.setText("Teléfono:");
        PanelCli.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 150, 30));

        jSeparator7.setForeground(new java.awt.Color(166, 163, 111));
        PanelCli.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 310, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(166, 163, 111));
        jLabel4.setText("Nombre:");
        PanelCli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 30));

        txtNombre.setBackground(new Color(0,0,0,0));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNombre.setText("Juan");
        txtNombre.setBorder(null);
        PanelCli.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 310, 40));

        tabla.setBackground(new java.awt.Color(255, 255, 204));
        tabla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tabla.setForeground(new java.awt.Color(102, 102, 102));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PROVEEDOR", "NOMBRE", "TELÉFONO", "DIRECCIÓN"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        PanelCli.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 720, 490));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(166, 163, 111));
        jLabel6.setText("Direción:");
        PanelCli.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 130, 30));

        jButton3.setBackground(new Color(0,0,0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, -1, -1));

        jButton7.setBackground(new Color(0,0,0,0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-C.png"))); // NOI18N
        jButton7.setText("x");
        jButton7.setBorder(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-CEP.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, -1, -1));
        PanelCli.add(txtidProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 290, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Panelproveedores.png"))); // NOI18N
        PanelCli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelCli);
        PanelCli.setBounds(0, 0, 1370, 920);

        setSize(new java.awt.Dimension(1349, 904));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
                dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
         agregar();
        limpiar();
         iniciar();
        fechaActual();
         nuevo();
    }//GEN-LAST:event_agregarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
         actualizar();
       limpiar();
       iniciar();
        fechaActual();
        nuevo();
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();
        limpiar();
         iniciar();
        fechaActual();
         nuevo();
    }//GEN-LAST:event_eliminarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       int fila=tabla.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }else{
           String idProvedor=tabla.getValueAt(fila, 0).toString();
           String Nombre=tabla.getValueAt(fila, 1).toString();
           String Telefono=tabla.getValueAt(fila, 3).toString();
           String Direccion=tabla.getValueAt(fila, 2).toString();

        
        txtidProveedor.setText(idProvedor);
        txtNombre.setText(Nombre);
        txtTelefono.setText(Telefono);
        txtdireccion.setText(Direccion);
      
        }
    }//GEN-LAST:event_tablaMouseClicked

     void iniciar(){
       listar();
       idAleatorio();
//        txtidEmpleado.setVisible(false);
   }
    void fechaActual(){
        
        String dia,mes,año;
        Calendar c= Calendar.getInstance();
        
        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH)+1);
        año = Integer.toString(c.get(Calendar.YEAR));
        
//        txtFechaHoy.setText(año+"-"+mes+"-"+dia);
        
    }
    
    void agregar(){
        String idProveedor=txtidProveedor.getText();
        String nombre=txtNombre.getText();
        String telefono=txtTelefono.getText();
        String direccion=txtdireccion.getText();
        
        Object[] ob=new Object[4];
        ob[0]=idProveedor;
        ob[1]=nombre;
        ob[2]=telefono;
        ob[3]=direccion;
        
         dao.add(ob);
    }
    
    void idAleatorio(){
        int numero = ThreadLocalRandom.current().nextInt(10000, 99999 + 1);
        txtidProveedor.setText(Integer.toString(numero));
        txtidProveedor.setEditable(false);
        txtidProveedor.setEnabled(false);
    }
    
  
        
    void actualizar(){
        int fila=tabla.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }else{
           String idProveedor=txtidProveedor.getText();
        String nombre=txtNombre.getText();
        String telefono=txtTelefono.getText();
        String direccion=txtdireccion.getText();
        
        Object[] ob=new Object[4];
           ob[3]=idProveedor;
           ob[0]=nombre;
           ob[1]=telefono;
            ob[2]=direccion;
            
        
         dao.actualizar(ob);
         System.out.println("exito");
        }      
       
    }
    void eliminar(){
         int fila=tabla.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }else{
            String idProveedor=tabla.getValueAt(fila, 0).toString();
            dao.eliminar(idProveedor);
        }
    }
    void listar(){
        List<Proveedor> lista=dao.listar();
        modelo=(DefaultTableModel)tabla.getModel();
        Object[]ob=new Object[4];
        for(int i=0;i< lista.size();i++){
            ob[0]=lista.get(i).getIdProveedor();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getTelefono();
            ob[3]=lista.get(i).getDireccion();
            
            modelo.addRow(ob);
        }
        
        tabla.setModel(modelo);
    }
    void nuevo(){
        txtNombre.setText("");
        txtTelefono.setText("");
        txtdireccion.setText("");
        txtNombre.requestFocus();
    }
    void limpiar(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCli;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtidProveedor;
    // End of variables declaration//GEN-END:variables
}
