package vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Proveedor;
import modelo.ProveedorDAO;
import vistas.Menu;

public class Proveedores extends javax.swing.JFrame {

    ProveedorDAO dao = new ProveedorDAO();
    Proveedor pv = new Proveedor();
    public String modo;

    DefaultTableModel modelo = new DefaultTableModel();

    public Proveedores() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        PanelCli.setBackground(new Color(0, 0, 0, 0));
        iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCli = new javax.swing.JPanel();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        txtdireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtidProveedor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        PanelCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setBackground(new Color(0,0,0,0));
        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizarpack.png"))); // NOI18N
        actualizar.setBorder(null);
        actualizar.setOpaque(false);
        actualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        PanelCli.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 760, 231, 70));

        eliminar.setBackground(new Color(0,0,0,0));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ELiminarpack.png"))); // NOI18N
        eliminar.setBorder(null);
        eliminar.setOpaque(false);
        eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarpack1.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        PanelCli.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 760, 231, 70));

        txtdireccion.setBackground(new Color(0,0,0,0));
        txtdireccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtdireccion.setBorder(null);
        PanelCli.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 515, 310, 30));

        txtTelefono.setBackground(new Color(0,0,0,0));
        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        PanelCli.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, 200, 30));

        agregar.setBackground(new Color(0,0,0,0));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar.png"))); // NOI18N
        agregar.setBorder(null);
        agregar.setOpaque(false);
        agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarP.png"))); // NOI18N
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        PanelCli.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 760, 231, 70));

        txtNombre.setBackground(new Color(0,0,0,0));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        PanelCli.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 330, 30));

        tabla.setBackground(new java.awt.Color(255, 255, 204));
        tabla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tabla.setForeground(new java.awt.Color(102, 102, 102));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PROVEEDOR", "NOMBRE", "TELÉFONO", "DIRECCIÓN"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        PanelCli.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 790, 560));

        jButton3.setBackground(new Color(0,0,0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButton7.setBackground(new Color(0,0,0,0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-C.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-CEP.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtidProveedor.setBackground(new Color(0,0,0,0));
        txtidProveedor.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        txtidProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidProveedor.setBorder(null);
        txtidProveedor.setOpaque(false);
        txtidProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidProveedorKeyTyped(evt);
            }
        });
        PanelCli.add(txtidProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 220, 200, 40));

        jButton2.setBackground(new Color(0,0,0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goemple.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goemple1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 900, 368, 130));

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iraProductos.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sombrairaproductos.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 900, 368, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProveedoresPanel.png"))); // NOI18N
        PanelCli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelCli);
        PanelCli.setBounds(0, 0, 1350, 1070);

        setSize(new java.awt.Dimension(1355, 1104));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        mn.mode = modo;
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        agregar();
        limpiar();
        iniciar();
      
        nuevo();
    }//GEN-LAST:event_agregarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        actualizar();
        limpiar();
        iniciar();
        
        nuevo();
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();
        limpiar();
        iniciar();
        
        nuevo();
    }//GEN-LAST:event_eliminarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            String idProvedor = tabla.getValueAt(fila, 0).toString();
            String Nombre = tabla.getValueAt(fila, 1).toString();
            String Telefono = tabla.getValueAt(fila, 3).toString();
            String Direccion = tabla.getValueAt(fila, 2).toString();

            txtidProveedor.setText(idProvedor);
            txtNombre.setText(Nombre);
            txtTelefono.setText(Telefono);
            txtdireccion.setText(Direccion);

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Productos pc = new Productos();
        pc.setVisible(true);
         pc.modo=modo;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Empleados Em = new Empleados();
        Em.setVisible(true);
         Em.modo=modo;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Diseño();
    }//GEN-LAST:event_formWindowActivated

    private void txtidProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidProveedorKeyTyped
       if( txtidProveedor.getText().length()==5){
            evt.consume();
        }
        
        char TipoTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtidProveedorKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char TipoTecla=evt.getKeyChar();
        if(Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
       if( txtTelefono.getText().length()>12){
            evt.consume();
        }
        
        char TipoTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    void Diseño() {
        if ("0".equals(modo)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProveedoresPanel.png"))); // NOI18N
        } else if ("1".equals(modo)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProveedorClaro.png"))); // NOI18N
        } else if ("2".equals(modo)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProveedoresDarkV.png"))); // NOI18N
        } else {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProvedoresDarkM.png"))); // NOI18N
        }
    }

    void iniciar() {
        listar();
        idAleatorio();

    }

  

    void agregar() {
        String idProveedor = txtidProveedor.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String direccion = txtdireccion.getText();

        Object[] ob = new Object[4];
        ob[0] = idProveedor;
        ob[1] = nombre;
        ob[2] = telefono;
        ob[3] = direccion;

        dao.add(ob);
    }

    void idAleatorio() {
        String idcli = dao.IdProductos();
        int id = Integer.valueOf(idcli);
        txtidProveedor.setText(Integer.toString(id + 1));
    }

    void actualizar() {
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            String idProveedor = txtidProveedor.getText();
            String nombre = txtNombre.getText();
            String telefono = txtTelefono.getText();
            String direccion = txtdireccion.getText();

            Object[] ob = new Object[4];
            ob[3] = idProveedor;
            ob[0] = nombre;
            ob[1] = telefono;
            ob[2] = direccion;

            dao.actualizar(ob);
            
        }

    }

    void eliminar() {
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            String idProveedor = tabla.getValueAt(fila, 0).toString();
            dao.eliminar(idProveedor);
        }
    }

    void listar() {
        List<Proveedor> lista = dao.listar();
        modelo = (DefaultTableModel) tabla.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getIdProveedor();
            ob[1] = lista.get(i).getNombre();
            ob[2] = lista.get(i).getTelefono();
            ob[3] = lista.get(i).getDireccion();

            modelo.addRow(ob);
        }

        tabla.setModel(modelo);
    }

    void nuevo() {
        txtNombre.setText("");
        txtTelefono.setText("");
        txtdireccion.setText("");
        txtNombre.requestFocus();
    }

    void limpiar() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCli;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtidProveedor;
    // End of variables declaration//GEN-END:variables
}
