package vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.EmpleadoDAO;
import java.awt.event.KeyEvent;
import modelo.UsuarioDAO;

public class RegistrarUsuario extends javax.swing.JFrame {

    String mode = "1";
    EmpleadoDAO dao = new EmpleadoDAO();
    UsuarioDAO udao = new UsuarioDAO();
    public String modo;

    public RegistrarUsuario() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        PanelCli.setBackground(new Color(0, 0, 0, 0));
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCli = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ComboNivel = new javax.swing.JComboBox<>();
        txtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pass2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        PanelCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new Color(0,0,0,0));
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        PanelCli.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 190, 30));

        txtDni.setBackground(new Color(0,0,0,0));
        txtDni.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtDni.setText("0000");
        txtDni.setBorder(null);
        txtDni.setOpaque(false);
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniKeyReleased(evt);
            }
        });
        PanelCli.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, 40));

        txtNombre.setBackground(new Color(0,0,0,0));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelCli.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 270, 40));

        jButton3.setBackground(new Color(0,0,0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-eliminarcli.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-eliminarcliP.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jButton4.setBackground(new Color(0,0,0,0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGAR.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGARp.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        ComboNivel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ComboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Administrador", "Vendedor", "Contabilidad" }));
        PanelCli.add(ComboNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 190, 40));

        txtid.setBackground(new Color(0,0,0,0));
        txtid.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelCli.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 130, 40));

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 40, 40));

        pass2.setBackground(new Color(0,0,0,0));
        pass2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        pass2.setBorder(null);
        pass2.setOpaque(false);
        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });
        PanelCli.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 190, 30));

        jButton2.setBackground(new Color(0,0,0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-C.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-CEP.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton6.setBackground(new Color(0,0,0,0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelCli.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        pass1.setBackground(new Color(0,0,0,0));
        pass1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        pass1.setBorder(null);
        pass1.setOpaque(false);
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        PanelCli.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addUser.png"))); // NOI18N
        PanelCli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 860));
        PanelCli.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 90, 30));

        getContentPane().add(PanelCli);
        PanelCli.setBounds(0, 0, 1010, 930);

        setSize(new java.awt.Dimension(951, 861));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarEmpleado();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed


    }//GEN-LAST:event_pass2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        add();
        limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Eliminar();
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed

    }//GEN-LAST:event_txtDniActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed

    }//GEN-LAST:event_pass1ActionPerformed

    private void txtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarEmpleado();
        }
    }//GEN-LAST:event_txtDniKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Empleados Em = new Empleados();
        Em.setVisible(true);
        Em.modo=modo;
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed
     void Diseño() {
        if ("0".equals(modo)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addUser.png"))); // NOI18N
        } else if ("1".equals(modo)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/claroUsuario.png"))); // NOI18N
        } else if ("2".equals(modo)) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DARKusuarioverde.png"))); // NOI18N
        } else {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioDark.png"))); // NOI18N
        }
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Diseño();
    }//GEN-LAST:event_formWindowActivated

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
         if( txtDni.getText().length()==5){
            evt.consume();
        }
        
        char TipoTecla=evt.getKeyChar();
        if(!Character.isDigit(TipoTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtDniKeyTyped
    void limpiar() {
        txtUsuario.setText("");
        pass2.setText("");
        pass1.setText("");
        txtid.setText("");
        txtNombre.setText("");
        txtDni.setText("");
        ComboNivel.setSelectedItem("Seleccionar");
    }

    void iniciar() {
        id.setVisible(false);
        txtNombre.setEditable(false);
        txtid.setEditable(false);
    }

    void Eliminar() {
        String idEmpleado = txtid.getText();
       
        udao.eliminarUsuario(idEmpleado);

    }

    

    String BuscarNivel() {
        String codNivel = (String) ComboNivel.getSelectedItem();
        String idNivel = null;
        if (codNivel.equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Seleccione una opción de Nivel");
        } else if (codNivel.equals("Administrador")) {
            idNivel = "01";
        } else if (codNivel.equals("Vendedor")) {
            idNivel = "02";
        } else {
            idNivel = "03";
        }

        return idNivel;
    }

    void buscarEmpleado() {
        int r;
        String IdEmpleado = txtDni.getText();
        if (txtDni.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar DNI del Usuario a registrar");
        } else {
            Empleado Empleado = dao.listarDNI(IdEmpleado);
            if (Empleado.getDNI() != null) {
                txtNombre.setText(Empleado.getNombre() + " " + Empleado.getApellido());
                txtid.setText(Empleado.getIdEmpleado());
                id.setText(Empleado.getIdEmpleado());
                ComboNivel.requestFocus();
            } else {
                r = JOptionPane.showConfirmDialog(this, "Empleado no registrado, Desea registrar");
                if (r == 0) {
                    Clientes Ct = new Clientes();
                    Ct.setVisible(true);
                    dispose();
                }
            }
        }

    }

    void add() {
       String Usuario = txtUsuario.getText();
        String pass = pass1.getText();
        String passc = pass2.getText();
        String idnivel = BuscarNivel();
        String idEmpleado = txtid.getText();
        

        
        
        if(passc.equals(pass)){
            Object[] ob = new Object[5];
        ob[0] = Usuario;
        ob[1] = pass;
        ob[2] = idnivel;
        ob[3] = idEmpleado;
        ob[4] = mode;
        udao.agregar(ob);
            
            JOptionPane.showMessageDialog(this,"Usuario agregado");
        }else{
            JOptionPane.showMessageDialog(this,"La contraseña no coincide");
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboNivel;
    private javax.swing.JPanel PanelCli;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
