/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ClienteDAO;
import modelo.DetalleVentas;
import modelo.Producto;
import modelo.ProductoDAO;
import modelo.Ventas;
import modelo.VentasDAO;
import vistas.Menu;

/**
 *
 * @author anthoni
 */
public class Venta extends javax.swing.JFrame {

    Cliente Cliente = new Cliente();
    ClienteDAO cdao = new ClienteDAO();
    ProductoDAO pdao = new ProductoDAO();
    VentasDAO vdao = new VentasDAO();
    Ventas Ventas = new Ventas();
    Producto p = new Producto();
    DetalleVentas dv=new DetalleVentas();

    DefaultTableModel modelo = new DefaultTableModel();
    String idP;
    double Tpagar;

    public Venta() {

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        PanelVentas.setBackground(new Color(0, 0, 0, 0));
        fechaActual();
         idAleatorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVentas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serie = new javax.swing.JTextField();
        txtNombrePr = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        buscarCl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        txtCodCli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtCodPro = new javax.swing.JTextField();
        buscarCod = new javax.swing.JButton();
        Cant = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        TotalaPagar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Stock = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtfechahoy = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idcliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IDDETALLE = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        PanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel3.setText("N° DE SERIE");
        PanelVentas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        serie.setBackground(new java.awt.Color(0, 153, 153));
        serie.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        PanelVentas.add(serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 40));

        txtNombrePr.setBackground(new java.awt.Color(162, 162, 151));
        txtNombrePr.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombrePr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombrePr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePrActionPerformed(evt);
            }
        });
        PanelVentas.add(txtNombrePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 380, 30));
        PanelVentas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 80, 10));

        buscarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/B.png"))); // NOI18N
        buscarCl.setBorder(null);
        buscarCl.setOpaque(false);
        buscarCl.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BP.png"))); // NOI18N
        buscarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClActionPerformed(evt);
            }
        });
        PanelVentas.add(buscarCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        tabla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "COD", "PRODUCTO", "CANTIDAD", "PRECIO UNI", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        PanelVentas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 810, 560));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setText("DNI Cliente:");
        PanelVentas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setText("Stock");
        PanelVentas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        txtcliente.setBackground(new java.awt.Color(162, 162, 151));
        txtcliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtcliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVentas.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 380, 30));
        PanelVentas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 220, 10));

        txtPrecio.setBackground(new Color(0,0,0,0));
        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtPrecio.setBorder(null);
        PanelVentas.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 80, 40));

        txtCodCli.setBackground(new Color(0,0,0,0));
        txtCodCli.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtCodCli.setText("58585858");
        txtCodCli.setBorder(null);
        PanelVentas.add(txtCodCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 220, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel6.setText("Precio:");
        PanelVentas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setText("COD. Producto:");
        PanelVentas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelVentas.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 790, -1, -1));

        txtCodPro.setBackground(new Color(0,0,0,0));
        txtCodPro.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtCodPro.setText("00001");
        txtCodPro.setBorder(null);
        PanelVentas.add(txtCodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 220, 30));

        buscarCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/B.png"))); // NOI18N
        buscarCod.setBorder(null);
        buscarCod.setOpaque(false);
        buscarCod.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BP.png"))); // NOI18N
        buscarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodActionPerformed(evt);
            }
        });
        PanelVentas.add(buscarCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        Cant.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelVentas.add(Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 70, 40));

        jButton3.setBackground(new Color(0,0,0,0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarp.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarF.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelVentas.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 710, -1, -1));

        TotalaPagar.setBackground(new java.awt.Color(153, 153, 153));
        TotalaPagar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        TotalaPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalaPagar.setText("15");
        TotalaPagar.setBorder(null);
        PanelVentas.add(TotalaPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 780, 140, 50));
        PanelVentas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 220, 10));

        Stock.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelVentas.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 80, 40));

        jButton7.setBackground(new Color(0,0,0,0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelVentas.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 50, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VE1.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setOpaque(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VE.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelVentas.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 790, -1, -1));

        txtfechahoy.setText("jTextField1");
        PanelVentas.add(txtfechahoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 100, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel8.setText("Cantidad:");
        PanelVentas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        idcliente.setText("jTextField1");
        PanelVentas.add(idcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Total a Pagar:");
        PanelVentas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 790, -1, -1));

        IDDETALLE.setText("jTextField1");
        PanelVentas.add(IDDETALLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 90, -1, -1));

        jButton6.setBackground(new Color(0,0,0,0));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-C.png"))); // NOI18N
        jButton6.setText("x");
        jButton6.setBorder(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(false);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN-CEP.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelVentas.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PanelVentas.png"))); // NOI18N
        PanelVentas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        getContentPane().add(PanelVentas);
        PanelVentas.setBounds(0, 0, 1370, 910);

        setSize(new java.awt.Dimension(1353, 901));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePrActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        guardarVenta();
        guardarDetallle();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void buscarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClActionPerformed
        buscarCliente();
    }//GEN-LAST:event_buscarClActionPerformed

    private void buscarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodActionPerformed
        buscarProductos();
    }//GEN-LAST:event_buscarCodActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        agregarProducto();
    }//GEN-LAST:event_jButton3ActionPerformed
    void guardarVenta() {
        String idVentas, idCliente, FechaVenta;
        double monto;

        idVentas = serie.getText();
        idCliente = idcliente.getText();
        FechaVenta = txtfechahoy.getText();
        monto = Double.parseDouble(TotalaPagar.getText());

        Ventas.setIdVentas(idVentas);
        Ventas.setIdCliente(idCliente);
        Ventas.setFechaVenta(FechaVenta);
        Ventas.setMonto(monto);
        vdao.GuradarVEntas(Ventas);

    }

    void guardarDetallle() {
        String idDetalleventa, idVentas, idProducto;
        int cantidad;
        double precioventa;
        
        idVentas = serie.getText();
        idProducto = txtCodPro.getText();
        
        
        for (int i = 0; i < tabla.getRowCount(); i++) {
            
             cantidad = Integer.parseInt( tabla.getValueAt(i, 3).toString());
             precioventa = (double) tabla.getValueAt(i, 5);
             idProducto = tabla.getValueAt(i, 1).toString();
             
        idDetalleventa = IDDETALLE.getText();
             
             System.out.println(idDetalleventa);
             System.out.println(idVentas);
             System.out.println(idProducto);
             System.out.println(cantidad);
             System.out.println(precioventa);
             System.out.println(i);
             
             dv.setIdDetalleventa(idDetalleventa);
             dv.setIdVentas(idVentas);
             dv.setIdProducto(idProducto);
             dv.setCantidad(cantidad);
             dv.setPrecioventa(precioventa);
             
             
             vdao.GuardarDetalleVentas(dv);
             int numero1 = ThreadLocalRandom.current().nextInt(10000, 99999 + 1);
        IDDETALLE.setText(Integer.toString(numero1));
             
             
        }
        
        
    }

    void fechaActual() {

        String dia, mes, año;
        Calendar c = Calendar.getInstance();

        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH) + 1);
        año = Integer.toString(c.get(Calendar.YEAR));

        txtfechahoy.setText(año + "-" + mes + "-" + dia);

    }

    void agregarProducto() {
        int item = 0;

        modelo = (DefaultTableModel) tabla.getModel();
        item = item + 1;

        String codPro = txtCodPro.getText();
        String nomPro = txtNombrePr.getText();
        int cant = (int) Cant.getValue();
        int stock = (int) Stock.getValue();
        double precio = Double.parseDouble(txtPrecio.getText());
        double total = precio * cant;

        ArrayList lista = new ArrayList();

        if (stock > 0) {
            lista.add(item);
            lista.add(codPro);
            lista.add(nomPro);
            lista.add(cant);
            lista.add(precio);
            lista.add(total);

            Object[] ob = new Object[6];
            ob[0] = lista.get(0);
            ob[1] = lista.get(1);
            ob[2] = lista.get(2);
            ob[3] = lista.get(3);
            ob[4] = lista.get(4);
            ob[5] = lista.get(5);
            modelo.addRow(ob);
            tabla.setModel(modelo);
            totalaPagar();
            
        } else {
            JOptionPane.showMessageDialog(this, "Stock no disponible");

        }

    }

    void totalaPagar() {
        int cant;
        double precio;
        Tpagar = 0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            cant = Integer.parseInt(tabla.getValueAt(i, 3).toString());
            precio = Double.parseDouble(tabla.getValueAt(i, 4).toString());
            System.out.println(cant);
            System.out.println(precio);
            Tpagar = Tpagar + (cant * precio);
        }
        TotalaPagar.setText("" + Tpagar);

    }

    void idAleatorio() {
        int numero = ThreadLocalRandom.current().nextInt(10000, 99999 + 1);
        serie.setText(Integer.toString(numero));
        int numero1 = ThreadLocalRandom.current().nextInt(10000, 99999 + 1);
        IDDETALLE.setText(Integer.toString(numero1));
        serie.setEditable(false);
        serie.setEnabled(false);
    }

    void buscarCliente() {
        int r;
        String cod = txtCodCli.getText();
        if (txtCodCli.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "debe ingresar cod cliente");
        } else {
            Cliente Cliente = cdao.listarID(cod);
            if (Cliente.getDNI() != null) {
                txtcliente.setText(Cliente.getNombre() + " " + Cliente.getApellido());
                idcliente.setText(Cliente.getIdCliente());
                txtCodPro.requestFocus();

            } else {
                r = JOptionPane.showConfirmDialog(this, "Cliente no registrado, Desea registrar");
                if (r == 0) {
                    Clientes Ct = new Clientes();
                    Ct.setVisible(true);
                    dispose();
                }
            }
        }
    }

    void buscarProductos() {
        int r;
        String cod = txtCodPro.getText();
        if (txtCodPro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "debe ingresar cod producto");
        } else {
            Producto Producto = pdao.listarID(cod);
            if (Producto.getIdProducto() != null) {
                txtNombrePr.setText(Producto.getNombre());
                txtPrecio.setText(String.valueOf(Producto.getPrecio()));
                Stock.setValue(Producto.getStock());
                txtCodPro.requestFocus();
            } else {
                r = JOptionPane.showConfirmDialog(this, "Producto no registrado, Desea registrar");
                if (r == 0) {
                    Productos Pt = new Productos();
                    Pt.setVisible(true);
                    dispose();
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Cant;
    private javax.swing.JTextField IDDETALLE;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JSpinner Stock;
    private javax.swing.JTextField TotalaPagar;
    private javax.swing.JButton buscarCl;
    private javax.swing.JButton buscarCod;
    private javax.swing.JTextField idcliente;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField serie;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCodCli;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtNombrePr;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtfechahoy;
    // End of variables declaration//GEN-END:variables
}
